INSERT INTO TDM_DOCAPPCODE_DEF (DOCAPP_CD,DOCAPP_CDNAME,REMARKS,REG_USERID,REG_DT,UPT_DT) VALUES
	 (1,'Approved',NULL,NULL,NULL,NULL),
	 (2,'Approved with comments',NULL,NULL,NULL,NULL),
	 (3,'Rejected',NULL,NULL,NULL,NULL);