INSERT INTO TMM_GB_REG (GB_CD,GB_NAME,GB_KR,REMARKS,REG_USERID,REG_DT,UPT_DT) VALUES
	 ('CN','CHINA','중국',NULL,NULL,NULL,NULL),
	 ('FR','FRANCE','프랑스',NULL,NULL,NULL,NULL),
	 ('GB','UNITED KINGDOM','영국',NULL,NULL,NULL,NULL),
	 ('GR','GREECE','그리스',NULL,NULL,NULL,NULL),
	 ('HR','CROATIA','크로아티아',NULL,NULL,NULL,NULL),
	 ('IN','INDIA','인도',NULL,NULL,NULL,NULL),
	 ('IT','ITALY','이탈리아',NULL,NULL,NULL,NULL),
	 ('JP','JAPAN','일본',NULL,NULL,NULL,NULL),
	 ('KR','KOREA','대한민국',NULL,NULL,NULL,NULL),
	 ('NO','NORWAY','노르웨이',NULL,NULL,NULL,NULL);
INSERT INTO TMM_GB_REG (GB_CD,GB_NAME,GB_KR,REMARKS,REG_USERID,REG_DT,UPT_DT) VALUES
	 ('PL','POLAND','폴란드',NULL,NULL,NULL,NULL),
	 ('RU','RUSSIAN FEDERATION','러시아',NULL,NULL,NULL,NULL),
	 ('US','UNITED STATES','미국',NULL,NULL,NULL,NULL);