INSERT INTO TMM_BUYERDEPT_REG (DEPT_CD,DEPT_NAME,DEPT_NAME_KR,REG_USERID,REG_DT,UPT_DT) VALUES
	 ('BAC','ACCOMMODATION','거주구',NULL,NULL,NULL),
	 ('BEL','ELECTRIC','전장',NULL,NULL,NULL),
	 ('BBA','BASIC','기본',NULL,NULL,NULL),
	 ('BST','STRUCTURE','구조',NULL,NULL,NULL),
	 ('BOU','OUFITTING','철의장',NULL,NULL,NULL),
	 ('BPI','PIPING','배관',NULL,NULL,NULL),
	 ('BMA','MACHINERY','기기',NULL,NULL,NULL),
	 ('BPA','PAINTING','도장',NULL,NULL,NULL);