INSERT INTO TMM_COMPDEPT_REG (DEPT_CD,DEPT_NAME,DEPT_NAME_KR,REG_USERID,REG_DT,UPT_DT) VALUES
	 ('AC','ACCOMMODATION DESIGN','선실설계',NULL,NULL,NULL),
	 ('AD','ADMINISTRATION OF DESIGN','설계운영',NULL,NULL,NULL),
	 ('BA','BASIC DESIGN','기본설계',NULL,NULL,NULL),
	 ('EL','ELECTRIC DESIGN','전장설계',NULL,NULL,NULL),
	 ('MA','MACHINERY DESIGN','기장설계',NULL,NULL,NULL),
	 ('OU','OUTFITTING DESIGN','의장설계',NULL,NULL,NULL),
	 ('PA','PAINTING DESIGN','도장설계',NULL,NULL,NULL),
	 ('PI','PIPING DESIGN','배관설계',NULL,NULL,NULL),
	 ('ST','STRUCTURE DESIGN','구조설계',NULL,NULL,NULL);